### ISSUE TITLE
Is `bz2_to_gz`still needed?

### ISSUE THREAD

**Issue by white-gecko** [Dockerizing/virtuoso-import-docker#1]
The `bz2_to_gz` method is not needed. According to the [Virtuoso documentation](http://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader) the importer can automatically expand bzip2 as well.

https://github.com/Dockerizing/virtuoso-import-docker/blob/c9f451bfdb251f1a24bfa8d51c17dbbc2b55dfff/import.sh#L59-L79

**Comment by white-gecko** [comment]
If we want to keep support for compressed graphs and if we remove the `bz2_to_gz`, we have to adjust the list of extensions accordingly:
https://github.com/Dockerizing/virtuoso-import-docker/blob/c9f451bfdb251f1a24bfa8d51c17dbbc2b55dfff/import.sh#L106

**Comment by TBoonX** [comment]
white-gecko do you have files to test the script?

**Comment by white-gecko** [comment]
Closed by 3e9d04b9e52a5cb5db4f4080ea4ea9a068415a6d

**Comment by white-gecko** [comment]
Actually xz and bz2 did not work only gz, so I think this was the reason for the function :-)
