### ISSUE TITLE
Encode virtuoso RDF dumps as UTF-8

### ISSUE THREAD

**Issue by TBoonX** [Dockerizing/virtuoso-import-docker#10]
The function 'dump_one_graph' stores file which are not UTF-8.
This results in "M\u00FCller, Carl August (*1860 \u20201928)" instead of "Müller, Carl August (*1860 †1928)".
We need an encoding script which handles this.

**Comment by white-gecko** [comment]
This can be fixed using a custom normalize script as it is also provided in the `normalize` directory.
