### ISSUE TITLE
Import from Git repository

### ISSUE THREAD

**Issue by white-gecko** [Dockerizing/virtuoso-import-docker#3]
We want to import data from git repositories (e.g. managed by a [QuitStore](http://github.com/AKSW/QuitStore)). The `restore.sh` seems to be some starting point. We should integrate the appropriate behavior with the `import.sh` to be actually accessible when running the docker image.

**Comment by TBoonX** [comment]
The first solution just adds 10 lines to the import script.
I want to enhance it in this milestone when working on the other issues.

**Comment by white-gecko** [comment]
The import from git repo works quit good.
