### ISSUE TITLE
Let the container automatically dump the data if the store is updated

### ISSUE THREAD

**Issue by white-gecko** [Dockerizing/virtuoso-import-docker#7]
Let the container dump the data periodically or on the event of updates on the store. The dump should happen to the git repository. #3 #5

**Comment by TBoonX** [comment]
In general we should use trigger in the database but I do not know which tables or Views have to be observed and how to execute a script from virtuoso.
Thus I will enhance the current cron job to either import or export.

**Comment by TBoonX** [comment]
@white-gecko please check the repo at 2398f97 and find out if the usage of the importer container works for you.

**Comment by white-gecko** [comment]
Now after 8a26f58c8327e0c653047b889e21cb9e2f06fdb6 and 503f91c14e06f48bc6769a169cde611693abceed the pushs actually work and the execution times for the cronjob are configurable.
